#ifndef POETIC_H
#define POETIC_H

#include "dictionary.h"

std::vector<std::vector<int>> techniques(std::vector<int> line, Dictionary& dictionary);

bool vowel_phenome_pred(std::string& str);

std::vector<std::string>::iterator vowel(std::vector<std::string>& syllable);


int num_shared_constants(std::vector<std::string> syllable1, std::vector<std::string> syllable2);

double cord_dist(const std::pair<int,int>& c1, const std::pair<int,int>& c2);

double vowel_dist(const std::string& vowel1, const std::string& vowel2);


// SCIENCE!
// The positioning of the jaw and tounge create a unique resonance cavity for the vibrations generated by the vocal chords
// This cavity produces a forment (natural mode) frequency spectra
// Place theory suggests that the ear distinguishes pitches based on the location of maximum excitation along the basilar membrane
// Thus we can distinguish formants and thus vowel sounds
// We can analyze the similarity of vowel sounds by how close their formants are
int techniques(std::vector<std::string>& syllable1, std::vector<std::string>& syllable2, const Stress stress1, const Stress stress2);


// ARARPABET    F1  F2
// AY   dipthong    850 1610 and IH
// AW   dipthong    850 1610 and UH
// EY   dipthong    390 2300 and IH
// IY   240 2400
// OW   dipthong    460 1310 and UH
// UW   250 595
// AE   900 2000
// AA   750 940
// AO   500 700
// OY   dipthong    AH and IH
// EH   610 1900
// ER   450 1600
// IH   400 2250
// UH   475 1250
// AH   600 1170

#endif //POETIC_H